baseURL = "https://example.com/"
# include content marked as draft
buildDrafts = false
# include content with publishdate in the future
buildFuture = false
# include content already expired
buildExpired = false
# enable this to make all relative URLs relative to content root. Note that this does not affect absolute URLs.
relativeURLs = true
disableRSS = true
enableRobotsTXT = true
editor = "nano"
languageCode = "en"
language = "en"
theme = "vncnt-hugo"
title = "Burhan Otour · Landing Page"

[blackfriday]
  extensions = ["hardLineBreak"]

[permalinks]
  fixed = ":title/"
  posts = "posts/:slug/"

[params]
  author = "Burhan Otour"
  email = "burhan.a.otour@hotmail.com"
  description = "Landing Page"
  bio = "Full Stack Software Engineer. \nBased in Germany :)"
  avatar = "img/avatar.jpg"
  favicon = "img/favicon.ico"
  error404 = "There is no such page."

  [params.contact]
    github = "https://github.com/BurhanOtour"
    instagram = "https://instagram.com/BurhanOtour"
    twitter = "https://twitter.com/BurhanAOtour"
    linkedin = "https://linkedin.com/in/burhanotour"
